### ISSUE TITLE
empty middleclass

### ISSUE THREAD

**Issue by rezabma** [siesta-project/siesta-sfl#7]
Hi Nick,
I have downloaded master version of flos. It seems that when I extract its zip file, the middleclass is empty! Could you please check it?
Thanks
Reza

**Comment by zerothi** [comment]
When you download the master zip, then you don't get the middleclass. Either download it manually or use git to retrieve it.   
When not using a release, you have to do: 
```bash
git clone --recursive <flos>
```
(depending on your git version).
